#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := HXM8

EXTRA_COMPONENT_DIRS = 	C:\Users\Matthew\OneDrive\Documents\Development\ESP8266\msys32\home\Matthew\esp\components\station\
C:\Users\Matthew\OneDrive\Documents\Development\ESP8266\msys32\home\Matthew\esp\components\MCP2515\
C:\Users\Matthew\OneDrive\Documents\Development\ESP8266\msys32\home\Matthew\esp\components\spi_master_HAL

include $(IDF_PATH)/make/project.mk
